### ISSUE TITLE
[bug] Application search is now worse in 21.10

### ISSUE THREAD

**Issue by skylord123** [pop-os/gnome-shell-extension-pop-cosmic#301]
Before upgrading to 21.10 I used to be able to search "sound" from the application search dialog to go to my sound settings. Now it gives me a bunch of results from the Pop!_Shop instead. I have to now search settings and then go to sound. 

I use a bluetooth headset daily at work and have to play with sound settings pretty frequently. It would be nice to have this fixed. It seems that you can't search for any settings pages anymore.

**Comment by leviport** [comment]
Are you searching in the applications library or in the launcher? In the launcher, sound settings are the first result for me. I'm not certain whether being able to search specific settings panels in the application library makes sense since settings panels aren't really standalone applications, but it could be something to consider.

**Comment by skylord123** [comment]
I'm searching in the Application Library (super + A).

It used to work before I upgraded to 21.10. Personally I would prefer the search to include as much as possible as it reduces time needed jumping through windows. Even searching "sound" in my phone application list gives me my sound settings despite it not being an actual standalone app.

**Comment by skylord123** [comment]
Wait, is super + a the Application Library or the Launcher?

**Comment by itsrachelfish** [comment]
Can confirm, the old applications launcher used to search through applications like settings and bring me directly to the relevant menu. The new applications launcher only shows me applications that are installed or can be installed. A big step backwards for user experience! (Also it looks way uglier, in my opinion) 

## Old applications launcher
The old launcher allowed me to search for pages within settings, like my monitor setup, sound settings, bluetooth settings, etc.

![old-launcher](https://user-images.githubusercontent.com/1670549/151870615-6a32c15a-607a-410d-a28c-29645845ee7b.jpeg)

## New applications launcher
The new launcher only displays applications

![new-launcher](https://user-images.githubusercontent.com/1670549/151870821-865dc9f8-4729-4337-b98e-68043553e600.png)

## Temporary solution
As a temporary solution I've switched to using the "launcher" instead of "applications", which still has the old behavior of searching through different settings menus.

![super-key-action](https://user-images.githubusercontent.com/1670549/151871240-3b371bff-f65b-4665-b530-d410c75d8b10.png)

![ugly-launcher](https://user-images.githubusercontent.com/1670549/151871472-f7b8d33c-40e8-42bd-8596-9be365b75622.png)

However, in my opinion this menu is a big step backwards from what it used to look like. If you go back to 20.04 the launcher, workspaces, and applications were all displayed together on a single menu when you pressed the super key. I do not see the benefit of splitting these into three separate options where you can only choose one.

**Comment by skylord123** [comment]
Yeah I realized I was using the application list instead of the launcher. Switching to the launcher has fixed this issue.

@itsrachelfish I miss the old functionality as well. Having the super key do all the things was far superior to this setup. I miss being able to tell my wife "press the super key" for launching or finding a window. There is an entire thread discussing this already: https://github.com/pop-os/cosmic/discussions/95#discussioncomment-2002486

I actually still really miss the old combined setup.

Since I was using the wrong menu I am just going to close this as using the launcher solves my searching issue.

**Comment by itsrachelfish** [comment]
@skylord123 for the sake of completeness it's worth noting that the "launcher" still does not provide all of the features that the  "super menu" had in 20.04. For example, when you used to type the word "lock" it would bring up the option to actually lock my screen.

![old-lock-behavior](https://user-images.githubusercontent.com/1670549/153325046-cb4589cc-78c5-424a-a645-dc3ed1c053de.jpeg)

However this new "launcher" only brings up settings for the screen lock, it doesn't actually let me lock my screen!

![new-lock-behavior](https://user-images.githubusercontent.com/1670549/153325191-168f6d74-94d5-41da-8938-1c01ef74a5b9.jpg)

That's why I only consider this new launcher a "temporary solution" - this is far from ideal! Definitely a step back in both UX and design. The old super menu would show me a list of my favorite programs, the windows I currently had open, my workspaces, AND let me search for an application to run. It was great

**Comment by leviport** [comment]
@itsrachelfish Not trying to weigh in with an argument, but I wanted to share a tip: `Super` + `Esc` is the default screen lock hotkey in Pop. Much fewer keystrokes than hitting `Super`, typing "lock", and hitting Enter. I use it constantly and it's very fast.

**Comment by mmstick** [comment]
@itsrachelfish A script for screen locking could be added. There's some scripts distributed with pop-launcher that you can see in `/usr/lib/pop-launcher/scripts/session/`, if you'd like to make your own custom actions to place in `/etc/pop-launcher/scripts/` or `~/.local/share/pop-launcher/scripts/`.

**Comment by itsrachelfish** [comment]
@leviport thanks for the tip! 

@mmstick appreciate the work-around but I already followed the instructions in the previously linked discussion thread to disable cosmic and replace it with the GNOME default behavior https://github.com/pop-os/cosmic/discussions/95#discussioncomment-1002048

:+1:
