### ISSUE TITLE
When dock is disabled, don't reserve space for it in Workspaces view

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/gnome-shell-extension-pop-cosmic#56]
When the dock is disabled, its space (on whichever edge of the screen it's configured for) is reserved but empty in the Workspaces overview.

Left example:
![Screenshot from 2021-05-27 09-52-06](https://user-images.githubusercontent.com/7199422/119858705-f3a43780-bed1-11eb-981d-bdcf1186e855.png)
![Screenshot from 2021-05-27 09-52-10](https://user-images.githubusercontent.com/7199422/119858720-f6069180-bed1-11eb-8515-3ec604196b16.png)

Right example:
![Screenshot from 2021-05-27 09-55-33](https://user-images.githubusercontent.com/7199422/119858736-f9018200-bed1-11eb-8788-9955eb6ff3cc.png)
![Screenshot from 2021-05-27 09-55-39](https://user-images.githubusercontent.com/7199422/119858741-fa32af00-bed1-11eb-9120-d6c5bfcfb80c.png)

Bottom example (issue doesn't seem to affect the windows vertically):
![Screenshot from 2021-05-27 09-51-44](https://user-images.githubusercontent.com/7199422/119858803-09b1f800-bed2-11eb-9f13-305872f364d1.png)
![Screenshot from 2021-05-27 09-51-53](https://user-images.githubusercontent.com/7199422/119858806-0a4a8e80-bed2-11eb-9a3b-2cab8871bd3b.png)

**Comment by WatchMkr** [comment]
I think this issue is related to other dock/workspace picker position overlap. See screenshots.
![Screenshot from 2021-06-24 08-19-41](https://user-images.githubusercontent.com/3430283/123279738-600c5980-d4c5-11eb-89e7-00d0cf6834fd.png)
![Screenshot from 2021-06-24 08-20-02](https://user-images.githubusercontent.com/3430283/123279747-613d8680-d4c5-11eb-91b4-6b1f9401b0f6.png)
![Screenshot from 2021-06-24 08-20-19](https://user-images.githubusercontent.com/3430283/123279749-61d61d00-d4c5-11eb-9114-cec1897d4e56.png)
![Screenshot from 2021-06-24 08-20-30](https://user-images.githubusercontent.com/3430283/123279753-626eb380-d4c5-11eb-914a-9517c3b80cee.png)

**Comment by jackpot51** [comment]
Please ensure the behavior is still there with this version: https://github.com/pop-os/gnome-shell-extension-ubuntu-dock/commit/00aed10387837c5b13b9b665abff00eccb79f76e

**Comment by jacobgkau** [comment]
I can recreate both of these issues with pop-os/gnome-shell-extension-ubuntu-dock@00aed10:

![Screenshot from 2021-06-24 13-52-31](https://user-images.githubusercontent.com/7199422/123324690-59490b00-d4f4-11eb-9f0d-465c4ddeb6d0.png)
![Screenshot from 2021-06-24 13-58-19](https://user-images.githubusercontent.com/7199422/123324693-5a7a3800-d4f4-11eb-8945-2a5d312216cd.png)

The first one's easy to recreate, the second one took a lot of fiddling before it started happening.

**Comment by WatchMkr** [comment]
I can confirm the overlap behavior occurs in the latest version
```carl@pop-os:~$ apt-cache policy gnome-shell-extension-ubuntu-dock
gnome-shell-extension-ubuntu-dock:
  Installed: 69ubuntu1pop0~1624393749~21.04~00aed10```
