### ISSUE TITLE
Rounded Corners - a general and optional setting

### ISSUE THREAD

**Issue by dxps** [pop-os/gnome-shell-extension-pop-cosmic#71]
Dear all,

I switched to Pop!_OS a couple of month ago, moving from an AwesomeWM + XFCE setup.
There I managed to get some very nice result: 9px like radius corners, good shadowing for a better focus, and so on.
To give you an example, here's what I still have on a laptop with that setup: 
![image](https://user-images.githubusercontent.com/14140226/121591607-5f45e300-ca42-11eb-84ff-63677fbb07ff.png)

But now I'm here, and seriously planning to stay! :blush: The overall experience of Pop!_OS is great.

I'd really like to have (and even contribute, if you enlight me a bit) some rounded corners on all windows (and corners).
And I'm not talking about nowadays huge Apple like rounded corners, so nothing that aggressive.

I know not everybody likes that, it's a subjective topic, that's why it should be an optional setting (provided or not through a Gnome extension?).

Any thoughts, ideas, and feedback, please?
Thanks!

**Comment by mjoork** [comment]
Unfortunately, it's not that easy in GNOME. I think GNOME 4 together with GTK 4 brings rounded corners on all sides of the application window (this requires the said application to be ported to GTK 4 though), but in the meanwhile, you can't control it that easily. One can get the rounding with a theme, but as [this guy calls out](https://www.reddit.com/r/gnome/comments/jyv3vr/it_is_possible_to_get_rounded_corners_on_gnome_338/gd87v8k?utm_source=share&utm_medium=web2x&context=3) in [this reddit post](https://www.reddit.com/r/gnome/comments/jyv3vr/it_is_possible_to_get_rounded_corners_on_gnome_338/?utm_source=share&utm_medium=web2x&context=3), it's not that easy either. One example of theme that does it is [Orchis](https://github.com/vinceliuice/Orchis-theme). Notice though, that [it still doesn't round Firefox](https://raw.githubusercontent.com/vinceliuice/Orchis-theme/master/src/firefox/preview02.png) (as it is not a pure GTK window?), resulting in an inconsistent look.

So everything above leads me into thinking that the only way is a custom composer (but GNOME uses Mutter and it is not replaceable?).

Correct me, if I am wrong.

I too would like to see the rounded corners in Pop OS, it's just that it has to be very stable, give expected results and be consistent with all windows. A lot of people actually struggle with getting rounded corners right on Linux, so supporting it on the OS level is something rather too complex and team has probably better things to work on than visual sugar. Just as a disclaimer: Mac OS always had rounded corners because there's no such variety of devices there as on Linux and their window manager/composer/GUI framework are one and only on Mac OS, so they don't concern themselves with compatibility with others.

**Comment by dxps** [comment]
Yeah, I am aware about the current state of things, and you're right also.
Probably we should hope that Pop!_OS will sooner switch to Gnome 40, as currently just a few distros (Fedora, OpenSuse, plus two others) embraced that journey.
And yes, hopefully, the apps will be upgraded to GTK 4.

**Comment by mjoork** [comment]
IMO this is not going to happen until Ubuntu switches to ver. 4 and its' latest release didn't, so it's very far in the future. I would search for a way to disable mutter (if it's possible) and run a custom composer.

**Comment by dxps** [comment]
That's true also, but at the same time, you can see that the upcoming Zorin OS 16 has these roundness and it's based on Mutter and Gnome 3. See [this moment](https://youtu.be/wm9eZT14978?t=361) specifically that shows this:
![image](https://user-images.githubusercontent.com/14140226/121727240-51e93100-caf4-11eb-85d4-a3083abef1d5.png)

I know, it's all based on some theming tricks and workarounds (even that terminal is a concrete example of not having it consistently everywhere), and having this natively is part of a Gnome 40 based future.

**Comment by Chinchzilla** [comment]
+1 I would like the corners to be more rounded as well, it would look fantastic with the Pop! theme

**Comment by dxps** [comment]
Right now I'm pretty happy with what I have:
![image](https://user-images.githubusercontent.com/14140226/162375619-b535f518-d99d-4687-a30f-fac153d838f7.png)

Using the [Graphite theme](https://github.com/vinceliuice/Graphite-gtk-theme), the Nordic dark flavor, I just changed a little bit to add more depth by having more darker shadows to improve the contrast.

**Comment by ghost** [comment]
I would also like to throw some support behind the idea of corner customization.  I came here to suggest the same thing.  

Corner roundness is a **defining** property of theme aesthetics.  It creates a general softness or hardness that shapes (no pun intended) the appearance of the entire desktop.

I personally hate big rounded corners, it's way too "soft" for my taste. But I'm also not a fan of perfectly sharp 90° corners either.  My happy place is a small radius to take the sharpness off, without so much roundness that it makes the desktop look like it was designed by Little Tikes.

There are three main theming options that I would like to see in my personal dream world of a desktop environment: 
* Overall theme: Light, Darker, Dark, OLED
* Accent color(s)
* Corners: Customizable integer corner radius setting applied across the desktop, or at least options like Smoother (20px), Smooth (10px), Sharper (4px), Sharp (0px) and "Theme Default"

These few characteristics give the user a lot of control over the general look and feel of their desktop, which is important.  It also makes user-created themes more versatile, as the end user doesn't have to take exactly what the theme designer gives them, but can tweak it and make it their own.

That's my 2¢

**Comment by namefailed** [comment]
This works for me.

https://extensions.gnome.org/extension/5237/rounded-window-corners/

**Comment by dxps** [comment]
@namefailed Indeed, Matt. 

Some months ago I switched back to Pop!_OS theme and used this lovely [Rounded Windows Corners](https://extensions.gnome.org/extension/5237/rounded-window-corners/) extension, besides [Just Perfection](https://gitlab.gnome.org/jrahmatzadeh/just-perfection) and some others.

For others who may get here, that's the option that we have, and it works just fine (especially the shadows control is absolute great).

Therefore, I'll close this ticket.
